.gitignore, LICENSE, bom/pom.xml, pom.xml
The PR is to setup project layout for the upcoming extensions.
=> Setup project layout for the upcoming extensions

pom.xml
Updates the extension to the latest Quarkus version
=> Bump to Quarkus 2.13.4

.github/dependabot.yml, .github/project.yml, .github/workflows/build.yml, .github/workflows/pre-release.yml, .github/workflows/quarkus-snapshot.yaml, .github/workflows/release.yml
These workflows are missing. When creating an extension for Quarkiverse, these workflows have to be set.
=> Adds intial workflows

docs/antora.yml, docs/modules/ROOT/nav.adoc, docs/modules/ROOT/pages/index.adoc, docs/pom.xml, docs/templates/includes/attributes.adoc
These Antora files are missing. When creating an extension for Quarkiverse, the documentation structure needs to be set.
=> Adds initial documentation

docs/modules/ROOT/pages/includes/attributes.adoc, docs/pom.xml, pom.xml
- Add dependencies to deployment modules
- Inject the BOM to enforce the versions
- Add the docs module back in parent pom.xml
=> Fix docs module execution

.github/workflows/build.yml, .github/workflows/pre-release.yml, .github/workflows/quarkus-snapshot.yaml, .github/workflows/release.yml
This contains fixes to support releasing from multiple branches and configures job concurrency appropriately
=> Update Workflow scripts

extensions/azure-app-configuration/runtime/src/main/resources/META-INF/quarkus-extension.yaml, extensions/azure-storage-blob/runtime/src/main/resources/META-INF/quarkus-extension.yaml, internal/core/runtime/src/main/resources/META-INF/quarkus-extension.yaml, internal/http-client-vertx/runtime/src/main/resources/META-INF/quarkus-extension.yaml, internal/jackson-dataformat-xml/runtime/src/main/resources/META-INF/quarkus-extension.yaml
modified:   extensions/azure-app-configuration/runtime/src/main/resources/META-INF/quarkus-extension.yaml
modified:   extensions/azure-storage-blob/runtime/src/main/resources/META-INF/quarkus-extension.yaml
modified:   internal/core/runtime/src/main/resources/META-INF/quarkus-extension.yaml
modified:   internal/http-client-vertx/runtime/src/main/resources/META-INF/quarkus-extension.yaml
modified:   internal/jackson-dataformat-xml/runtime/src/main/resources/META-INF/quarkus-extension.yaml
=> On branch edburns-msft-rh-359-add-icon-url

.github/project.yml, docs/modules/ROOT/pages/includes/attributes.adoc
=> Release 1.0.0

.github/project.yml, docs/modules/ROOT/pages/includes/attributes.adoc
* release 1.0.0
* fix build failure https://github.com/quarkiverse/quarkus-azure-services/actions/runs/5440431581/jobs/9893343502
---------
=> Release 1.0.0 (#132)

bom/pom.xml, docs/modules/ROOT/pages/includes/quarkus-azure-storage-blob.adoc, extensions/azure-app-configuration/deployment/src/main/java/io/quarkiverse/azure/app/configuration/deployment/AzureAppConfigurationProcessor.java, extensions/azure-storage-blob/deployment/src/main/java/io/quarkiverse/azure/storage/blob/deployment/DevServicesStorageBlobProcessor.java, extensions/azure-storage-blob/deployment/src/test/java/io/quarkiverse/azure/storage/blob/deployment/StorageBlobTestResource.java
This should upgrade the SDK BOM correctly
- Azurite needs to be upgraded to latest version 3.28.0
- ConfigurationSettingPage in Azure-data-appconfiguration in Azure Java SDK has been remove moving from 1.4.x to 1.5.x
All tests are green locally
=> Upgrade Azure SDK BOM to version 1.2.19

.github/build-with-maven-native.sh, docs/modules/ROOT/pages/includes/quarkus-azure-app-configuration.adoc, extensions/azure-app-configuration/runtime/src/main/java/io/quarkiverse/azure/app/configuration/AzureAppConfigurationConfig.java, extensions/azure-app-configuration/runtime/src/main/java/io/quarkiverse/azure/app/configuration/AzureAppConfigurationConfigSourceFactory.java, integration-tests/README.md, integration-tests/azure-app-configuration/README.md, integration-tests/azure-app-configuration/src/test/java/io/quarkiverse/azure/app/configuration/it/AzureAppConfigurationResource.java, integration-tests/azure-app-configuration/src/test/java/io/quarkiverse/azure/app/configuration/it/AzureAppConfigurationWithLabelsExternalIT.java, integration-tests/azure-app-configuration/src/test/java/io/quarkiverse/azure/app/configuration/it/AzureAppConfigurationWithLabelsTest.java, integration-tests/azure-app-configuration/src/test/java/io/quarkiverse/azure/app/configuration/it/LabelsConfigurationProfile.java, integration-tests/azure-app-configuration/src/test/resources/response.json, integration-tests/azure-app-configuration/src/test/resources/response_prod.json
=> Support filtering by labels for App Configuration extension

extensions/azure-storage-blob/deployment/pom.xml, internal/jackson-dataformat-xml/deployment/src/main/java/io/quarkiverse/azure/jackson/datafromat/xml/deployment/JacksonDataformatXmlSupportProcessor.java
See https://github.com/quarkiverse/quarkus-azure-services/issues/205 and https://github.com/quarkiverse/quarkus-cxf/issues/1257.
=> Fix issue-205

extensions/azure-storage-blob/runtime/src/main/java/io/quarkiverse/azure/storage/blob/runtime/StorageBlobServiceClientProducer.java, integration-tests/azure-storage-blob/pom.xml, integration-tests/azure-storage-blob/src/main/java/io/quarkiverse/azure/storage/blob/it/StorageBlobAsyncResource.java, integration-tests/azure-storage-blob/src/main/java/io/quarkiverse/azure/storage/blob/it/StorageBlobResource.java, integration-tests/azure-storage-blob/src/test/java/io/quarkiverse/azure/storage/blob/it/StorageBlobAsyncResourceIT.java, integration-tests/azure-storage-blob/src/test/java/io/quarkiverse/azure/storage/blob/it/StorageBlobAsyncResourceTest.java
The PR is to address the issue #181 by supporting async client for azure-storage-blob extension.
Test is passed: https://github.com/majguo/quarkus-azure-services/actions/runs/8865630787.
=> Support storage blob async client

.github/project.yml, docs/modules/ROOT/pages/includes/attributes.adoc
@galiacheng @edburns @backwind1233 @m-reza-rahman
=> Release 1.0.3

.github/workflows/build.yml, .github/workflows/quarkus-snapshot.yaml
Fix the CI pipeline failure `Client assertion is not within its valid time range`, see https://github.com/quarkiverse/quarkus-azure-services/actions/runs/8918860899/job/24494151090.
=> Fix error: Client assertion is not within its valid time range

docs/modules/ROOT/pages/quarkus-azure-key-vault.adoc, integration-tests/README.md, integration-tests/azure-keyvault/README.md
=> [Follow up] Apply fix from #251

.github/project.yml, docs/modules/ROOT/pages/includes/attributes.adoc, integration-tests/azure-app-configuration/README.md, integration-tests/azure-keyvault/README.md, integration-tests/azure-storage-blob/README.md
This pull request updates the project version from `1.0.5` to `1.0.6` across multiple files to ensure consistency throughout the documentation and configuration files.
* [`.github/project.yml`](diffhunk://#diff-735957720c86e5ec3ee129d26dde30a1fd6b7e485100843ef9b576269eb065e9L2-R2): Updated `current-version` to `1.0.6`.
* [`docs/modules/ROOT/pages/includes/attributes.adoc`](diffhunk://#diff-6a9cf7ce7ec74bc87cf4d9b920b636a61915b0ad2683689d9ee8280a1debbf37L1-R1): Updated `:project-version:` attribute to `1.0.6`.
* [`integration-tests/azure-app-configuration/README.md`](diffhunk://#diff-e0cabaff689084ec2c6cc8b0b114c5e905b74e2825b9539493819e9778551596L36-R44): Updated example version in the `pom.xml` file to `1.0.6`.
* …
=> Release 1.0.6

.github/delete-azure-resources.sh, .github/run-integration-test.sh, .github/workflows/quarkus-snapshot.yaml, docs/modules/ROOT/pages/includes/quarkus-azure-storage-blob.adoc, docs/modules/ROOT/pages/includes/quarkus-azure-storage-blob_quarkus.azure.adoc, docs/modules/ROOT/pages/quarkus-azure-cosmos.adoc, docs/modules/ROOT/pages/quarkus-azure-eventhubs.adoc, docs/modules/ROOT/pages/quarkus-azure-storage-blob.adoc, extensions/azure-storage-blob/deployment/pom.xml, extensions/azure-storage-blob/deployment/src/main/java/io/quarkiverse/azure/storage/blob/deployment/DevServicesStorageBlobProcessor.java, extensions/azure-storage-blob/runtime/pom.xml, extensions/azure-storage-blob/runtime/src/main/java/io/quarkiverse/azure/storage/blob/runtime/StorageBlobConfig.java, extensions/azure-storage-blob/runtime/src/main/java/io/quarkiverse/azure/storage/blob/runtime/StorageBlobServiceClientProducer.java, integration-tests/azure-cosmos/README.md, integration-tests/azure-eventhubs/README.md, integration-tests/azure-storage-blob/README.md, pom.xml
This pull request includes several changes to the Azure integration and documentation in the project. The most significant changes involve enhancements to the authentication methods for **Azure Storage Blob** service and updates to the documentation to reflect these changes.
* [`extensions/azure-storage-blob/runtime/src/main/java/io/quarkiverse/azure/storage/blob/runtime/StorageBlobConfig.java`](diffhunk://#diff-ef270aaccb8cd078c480b569730c9e73c8e44076940f02d134dc93808f8f47e5L21-R28): Added a new configuration property for the Azure Storage Blob endpoint.
* [`extensions/azure-storage-blob/deployment/src/main/java/io/quarkiverse/azure/storage/blob/deployment/DevServicesStorageBlobProcessor.java`](diffhunk://#diff-c1fc4fced87f25fb3efa03ebe1b248eb12adf8378cd3d8b1620ac9105eea1ff5L41-R42): …
=> Support Microsoft Entra ID authentication and authorization for azure-storage-blob extension

.github/project.yml, docs/modules/ROOT/pages/includes/attributes.adoc, integration-tests/azure-app-configuration/README.md, integration-tests/azure-cosmos/README.md, integration-tests/azure-eventhubs/README.md, integration-tests/azure-keyvault/README.md, integration-tests/azure-storage-blob/README.md
This pull request updates the project version from `1.0.7` to `1.0.8` across various files and documentation. The changes ensure that the entire project is consistent with the new version.
* [`.github/project.yml`](diffhunk://#diff-735957720c86e5ec3ee129d26dde30a1fd6b7e485100843ef9b576269eb065e9L2-R2): Updated `current-version` to `1.0.8`.
* [`docs/modules/ROOT/pages/includes/attributes.adoc`](diffhunk://#diff-6a9cf7ce7ec74bc87cf4d9b920b636a61915b0ad2683689d9ee8280a1debbf37L1-R1): Updated `:project-version:` to `1.0.8`.
* [`integration-tests/azure-app-configuration/README.md`](diffhunk://#diff-e0cabaff689084ec2c6cc8b0b114c5e905b74e2825b9539493819e9778551596L36-R44): Updated example version to `1.0.8` in the `pom.xml` snippet.
* …
=> Release 1.0.8

.github/run-integration-test.sh, README.md, docs/modules/ROOT/pages/quarkus-azure-cosmos.adoc
This pull request includes changes to the integration test script, README documentation, and an example application. The most important changes focus on improving the integration test process and updating documentation references.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L3-R3): Removed the branch query parameter from the build badge URL to simplify the badge link.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L49-R49): Updated the example pull request reference for releasing a new version to point to a more recent pull request.
* [`docs/modules/ROOT/pages/quarkus-azure-cosmos.adoc`](diffhunk://#diff-025098588d9e30823b345507584ff18919a5e3022b62e090fce15425d702d970R198): Added a new …
=> A few refinements

.github/project.yml, docs/modules/ROOT/pages/includes/attributes.adoc, integration-tests/azure-app-configuration/README.md, integration-tests/azure-cosmos/README.md, integration-tests/azure-eventhubs/README.md, integration-tests/azure-keyvault/README.md, integration-tests/azure-services-together/README.md, integration-tests/azure-storage-blob/README.md
This pull request includes multiple changes to update the project version from `1.0.8` to `1.0.9` across various files and documentation. The most important changes include updates to the version number in configuration files and documentation references.
* [`.github/project.yml`](diffhunk://#diff-735957720c86e5ec3ee129d26dde30a1fd6b7e485100843ef9b576269eb065e9L2-R2): Updated `current-version` from `1.0.8` to `1.0.9`.
* [`docs/modules/ROOT/pages/includes/attributes.adoc`](diffhunk://#diff-6a9cf7ce7ec74bc87cf4d9b920b636a61915b0ad2683689d9ee8280a1debbf37L1-R1): Updated `:project-version:` from `1.0.8` to `1.0.9`.
* [`integration-tests/azure-app-configuration/README.md`](diffhunk://#diff-e0cabaff689084ec2c6cc8b0b114c5e905b74e2825b9539493819e9778551596L3 …
=> Release 1.0.9

.github/run-integration-test.sh, docs/modules/ROOT/pages/includes/quarkus-azure-app-configuration.adoc, docs/modules/ROOT/pages/includes/quarkus-azure-app-configuration_quarkus.azure.adoc, docs/modules/ROOT/pages/quarkus-azure-app-configuration.adoc, extensions/azure-app-configuration/deployment/pom.xml, extensions/azure-app-configuration/runtime/pom.xml, extensions/azure-app-configuration/runtime/src/main/java/io/quarkiverse/azure/app/configuration/AzureAppConfigurationConfig.java, extensions/azure-app-configuration/runtime/src/main/java/io/quarkiverse/azure/app/configuration/AzureAppConfigurationConfigSourceFactory.java, integration-tests/azure-app-configuration/README.md, integration-tests/azure-services-together/README.md, internal/azure-identity/deployment/pom.xml, internal/azure-identity/runtime/pom.xml
This pull request introduces several changes to the Azure App Configuration integration, including updates to the authentication process, documentation, and dependencies. The main focus is on adding support for Microsoft Entra ID authentication.
* [`extensions/azure-app-configuration/runtime/src/main/java/io/quarkiverse/azure/app/configuration/AzureAppConfigurationConfig.java`](diffhunk://#diff-d27946b6bc2264947ff9811120c9f5689279077c527e5bca0b3f35e6574b6dc2L21-R46): Updated to support authentication with Microsoft Entra ID and access keys.
* [`extensions/azure-app-configuration/runtime/src/main/java/io/quarkiverse/azure/app/configuration/AzureAppConfigurationConfigSourceFactory.java`](diffhunk://#diff-0a67e7d6a45ab8889da1212b0b7973096c65129c7381804b91cac3e8fd0aa5c2R48-R61): Modified to …
=> Support Microsoft Entra ID auth for extension App Configuration

.github/project.yml, docs/modules/ROOT/pages/includes/attributes.adoc, integration-tests/azure-app-configuration/README.md, integration-tests/azure-cosmos/README.md, integration-tests/azure-eventhubs/README.md, integration-tests/azure-keyvault/README.md, integration-tests/azure-services-together/README.md, integration-tests/azure-storage-blob/README.md
This pull request includes updates to several files to reflect the new version `1.1.1` of the Quarkus Azure services extensions. The changes ensure that the documentation and configuration files are aligned with the latest release version.
* [`.github/project.yml`](diffhunk://#diff-735957720c86e5ec3ee129d26dde30a1fd6b7e485100843ef9b576269eb065e9L2-R2): Updated `current-version` from `1.1.0` to `1.1.1`.
* [`docs/modules/ROOT/pages/includes/attributes.adoc`](diffhunk://#diff-6a9cf7ce7ec74bc87cf4d9b920b636a61915b0ad2683689d9ee8280a1debbf37L1-R1): Updated `:project-version:` from `1.1.0` to `1.1.1`.
* [`integration-tests/azure-app-configuration/README.md`](diffhunk://#diff-e0cabaff689084ec2c6cc8b0b114c5e905b74e2825b9539493819e9778551596L36-R44): Updated …
=> Release 1.1.1

common/azure-identity/deployment/pom.xml, common/azure-identity/runtime/pom.xml, services/azure-app-configuration/deployment/pom.xml
This pull request includes several changes to the `pom.xml` files in different modules, primarily focusing on dependency updates and removals.
Dependency updates and removals:
* [`common/azure-identity/deployment/pom.xml`](diffhunk://#diff-4d65ee8211924edbb3aef8ac1a39487b89cb87b01a837486a3857656203df8d2L17-R17): Updated the `quarkus-arc-deployment` dependency to `quarkus-core-deployment`.
* [`common/azure-identity/runtime/pom.xml`](diffhunk://#diff-29139017a3cd52c08e49047493250bddcb06513925edcfbb997ec637b26e0488L29-L33): Removed the `graal-sdk` dependency.
* [`services/azure-app-configuration/deployment/pom.xml`](diffhunk://#diff-852854fd7086ac0b3177318b29a4b7e84471610aa6935f9c8afd9ef5e3b7e913L57-L61): Removed the `quarkus-arc-deployment` test dependency.
integration test passed: …
=> Clean up dependencies for extensions

.github/project.yml, docs/modules/ROOT/pages/includes/attributes.adoc, integration-tests/azure-app-configuration/README.md, integration-tests/azure-cosmos/README.md, integration-tests/azure-eventhubs/README.md, integration-tests/azure-keyvault/README.md, integration-tests/azure-services-together/README.md, integration-tests/azure-storage-blob/README.md
This pull request includes version updates across multiple files to reflect the new release version `1.1.2`. The changes ensure consistency in documentation and configuration files.
* [`.github/project.yml`](diffhunk://#diff-735957720c86e5ec3ee129d26dde30a1fd6b7e485100843ef9b576269eb065e9L2-R2): Updated `current-version` to `1.1.2`.
* [`docs/modules/ROOT/pages/includes/attributes.adoc`](diffhunk://#diff-6a9cf7ce7ec74bc87cf4d9b920b636a61915b0ad2683689d9ee8280a1debbf37L1-R1): Updated `:project-version:` to `1.1.2`.
* [`integration-tests/azure-app-configuration/README.md`](diffhunk://#diff-e0cabaff689084ec2c6cc8b0b114c5e905b74e2825b9539493819e9778551596L36-R44): Updated example version to `1.1.2` in the `pom.xml` snippet.
* …
=> Release 1.1.2

README.md
=> readme: add compatibility matrix

docs/modules/ROOT/pages/includes/quarkus-azure-cosmos.adoc, docs/modules/ROOT/pages/includes/quarkus-azure-cosmos_quarkus.azure.adoc, services/azure-cosmos/deployment/pom.xml, services/azure-cosmos/deployment/src/main/java/io/quarkiverse/azure/cosmos/deployment/CosmosBuildTimeConfig.java, services/azure-cosmos/deployment/src/main/java/io/quarkiverse/azure/cosmos/deployment/CosmosDevServicesConfig.java, services/azure-cosmos/deployment/src/main/java/io/quarkiverse/azure/cosmos/deployment/DevServicesCosmosProcessor.java, services/azure-cosmos/deployment/src/test/java/io/quarkiverse/azure/cosmos/deployment/CosmosResource.java, services/azure-cosmos/deployment/src/test/java/io/quarkiverse/azure/cosmos/deployment/CosmosResourceTest.java, services/azure-cosmos/runtime/src/main/java/io/quarkiverse/azure/cosmos/runtime/CosmosClientProducer.java, services/azure-cosmos/runtime/src/main/java/io/quarkiverse/azure/cosmos/runtime/CosmosConfig.java
Note: Most of this is cargo-culted esp from the blob service, so please review and advise. I'm fairly new to Quarkus.
Todo:
Closes https://github.com/quarkiverse/quarkus-azure-services/issues/363
=> Add DevService for CosmosDB

.github/project.yml, README.md, docs/modules/ROOT/pages/includes/attributes.adoc, integration-tests/azure-app-configuration/README.md, integration-tests/azure-cosmos/README.md, integration-tests/azure-eventhubs/README.md, integration-tests/azure-keyvault/README.md, integration-tests/azure-services-together/README.md, integration-tests/azure-storage-blob/README.md
This pull request includes a series of updates to various documentation files to reflect the new version `1.1.3` of the Quarkus Azure services extensions. The changes ensure that all references to the previous version `1.1.2` are updated to the new version.
* [`.github/project.yml`](diffhunk://#diff-735957720c86e5ec3ee129d26dde30a1fd6b7e485100843ef9b576269eb065e9L2-R2): Updated the `current-version` from `1.1.2` to `1.1.3`.
* [`docs/modules/ROOT/pages/includes/attributes.adoc`](diffhunk://#diff-6a9cf7ce7ec74bc87cf4d9b920b636a61915b0ad2683689d9ee8280a1debbf37L1-R1): Updated the `project-version` attribute from `1.1.2` to `1.1.3`.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R64): Added a new row to …
=> Release 1.1.3

README.md, docs/modules/ROOT/nav.adoc, docs/modules/ROOT/pages/index.adoc, docs/modules/ROOT/pages/quarkus-azure-cosmos.adoc, docs/modules/ROOT/pages/quarkus-azure-eventhubs.adoc, docs/modules/ROOT/pages/quarkus-azure-servicebus.adoc, docs/pom.xml, integration-tests/azure-servicebus/README.md
The major goal of the PR is to add integration test sample readme and doc for `azure-servicebus` extension.
It also corrects typo for other docs in the last commit.
@albers @backwind1233
=> Integration test sample readme and doc for azure-servicebus

docs/modules/ROOT/pages/includes/quarkus-azure-servicebus.adoc, docs/modules/ROOT/pages/includes/quarkus-azure-servicebus_quarkus.azure.adoc, services/azure-servicebus/deployment/src/main/java/io/quarkiverse/azure/servicebus/deployment/ServiceBusDevServicesConfig.java, services/azure-servicebus/deployment/src/main/java/io/quarkiverse/azure/servicebus/deployment/ServiceBusDevServicesProcessor.java, services/azure-servicebus/deployment/src/test/java/io/quarkiverse/azure/servicebus/deployment/DeploymentWithDevServicesTest.java, services/azure-servicebus/deployment/src/test/java/io/quarkiverse/azure/servicebus/deployment/DeploymentWithSuppressedDevServicesTest.java
The term "license" is more commonly used in international communication.
=> Rename licence to license

.github/project.yml, README.md, docs/modules/ROOT/pages/includes/attributes.adoc, integration-tests/azure-app-configuration/README.md, integration-tests/azure-cosmos/README.md, integration-tests/azure-eventhubs/README.md, integration-tests/azure-keyvault/README.md, integration-tests/azure-servicebus/README.md, integration-tests/azure-services-together/README.md, integration-tests/azure-storage-blob/README.md, pom.xml
This pull request updates the project version from `1.1.5` to `1.1.6` across multiple files and documentation. The changes ensure consistency in versioning throughout the project and its integration tests.
* [`.github/project.yml`](diffhunk://#diff-735957720c86e5ec3ee129d26dde30a1fd6b7e485100843ef9b576269eb065e9L2-R2): Updated `current-version` from `1.1.5` to `1.1.6`.
* [`docs/modules/ROOT/pages/includes/attributes.adoc`](diffhunk://#diff-6a9cf7ce7ec74bc87cf4d9b920b636a61915b0ad2683689d9ee8280a1debbf37L1-R1): Updated `:project-version:` attribute from `1.1.5` to `1.1.6`.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R66): Added compatibility details for version `1.1.6` in the extensions compatibility matrix.
* Integration test README …
=> Release 1.1.6

.github/project.yml, README.md, docs/modules/ROOT/pages/includes/attributes.adoc, integration-tests/azure-app-configuration/README.md, integration-tests/azure-cosmos/README.md, integration-tests/azure-eventhubs/README.md, integration-tests/azure-keyvault/README.md, integration-tests/azure-servicebus/README.md, integration-tests/azure-services-together/README.md, integration-tests/azure-storage-blob/README.md
This pull request updates the project version from `1.1.6` to `1.1.7` across multiple files and documentation. The changes ensure consistency in versioning and update references to the latest release.
* Updated the `current-version` in `.github/project.yml` from `1.1.6` to `1.1.7`.
* Changed the `:project-version:` attribute in `docs/modules/ROOT/pages/includes/attributes.adoc` to `1.1.7`.
* Added compatibility information for version `1.1.7` in the compatibility matrix in `README.md`.
* Updated references to version `1.1.7` in the `pom.xml` examples in the README files for integration tests:
- `integration-tests/azure-app-configuration/README.md`
- `integration-tests/azure-cosmos/README.md`
- `integration-tests/azure-eventhubs/README.md`
- `integration-tests/azure-keyvault/README.md`
- …
=> Release 1.1.7

.github/project.yml, README.md, docs/modules/ROOT/pages/includes/attributes.adoc, integration-tests/azure-app-configuration/README.md, integration-tests/azure-cosmos/README.md, integration-tests/azure-eventhubs/README.md, integration-tests/azure-keyvault/README.md, integration-tests/azure-servicebus/README.md, integration-tests/azure-services-together/README.md, integration-tests/azure-storage-blob/README.md
This pull request updates the documentation and configuration files to reference the new release version `1.1.8` of Quarkus Azure services. The changes ensure consistency across project metadata, documentation, and integration test instructions.
Version updates and documentation:
* Updated the current release version to `1.1.8` in `.github/project.yml` and `docs/modules/ROOT/pages/includes/attributes.adoc`. [[1]](diffhunk://#diff-735957720c86e5ec3ee129d26dde30a1fd6b7e485100843ef9b576269eb065e9L2-R2) [[2]](diffhunk://#diff-6a9cf7ce7ec74bc87cf4d9b920b636a61915b0ad2683689d9ee8280a1debbf37L1-R1)
* Added a new row for version `1.1.8` in the compatibility matrix in `README.md`.
Integration test instructions:
* Updated integration test `README.md` files for Azure App Configuration, Cosmos, Event …
=> Release 1.1.8

.github/project.yml, README.md, docs/modules/ROOT/pages/includes/attributes.adoc, integration-tests/azure-app-configuration/README.md, integration-tests/azure-cosmos/README.md, integration-tests/azure-eventhubs/README.md, integration-tests/azure-keyvault/README.md, integration-tests/azure-servicebus/README.md, integration-tests/azure-services-together/README.md, integration-tests/azure-storage-blob/README.md
This pull request updates the project version from 1.1.8 to 1.1.9 throughout the repository. The changes ensure that documentation, configuration files, and integration test instructions all reference the new release version.
Version bump and documentation updates:
* Updated the project version to `1.1.9` in `.github/project.yml` and `docs/modules/ROOT/pages/includes/attributes.adoc` to reflect the new release. [[1]](diffhunk://#diff-735957720c86e5ec3ee129d26dde30a1fd6b7e485100843ef9b576269eb065e9L2-R2) [[2]](diffhunk://#diff-6a9cf7ce7ec74bc87cf4d9b920b636a61915b0ad2683689d9ee8280a1debbf37L1-R1)
* Added a new row for version `1.1.9` in the compatibility matrix in `README.md`, showing the corresponding Quarkus and Java versions.
Integration test documentation:
* Updated all integration …
=> Release 1.1.9
