quarkiverse/quarkus-azure-services

storage-blob/runtime/src/main/java/io/quarkiverse/azureservices/azure/storage/blob/runtime/StorageBlobServiceClientProducer.java

When using CDI (which is the case of Quarkus), `@ApplicationScoped` is preferred to `@Singleton`. 
Getting rid of `@Default` as it is by default.

Prefer ApplicationScoped to Singleton when using CDI

---

pom.xml
storage-blob/deployment/pom.xml
storage-blob/runtime/pom.xml

Getting rid of Camel dependency because `http-vertx` is already in `azue-core`. Replacing `camel-quarkus-support-azure-core-http-client-vertx` with `azure-core-http-vertx`

Getting rid of Camel dependency

---

storage-blob/deployment/pom.xml

Running `mvn dependency:analyze` and moving dependencies that are only used in test to `test` scope

Changing dependency scope to test

---

extensions/core/deployment/src/main/java/io/quarkiverse/azureservices/core/deployment/AzureCoreSupportProcessor.java
extensions/core/runtime/src/main/resources/META-INF/quarkus-extension.yaml
extensions/http-client-vertx/deployment/src/main/java/io/quarkiverse/azureservices/core/http/vertx/deployment/AzureCoreHttpClientVertxProcessor.java
extensions/http-client-vertx/runtime/src/main/java/io/quarkiverse/azureservices/core/http/vertx/runtime/QuarkusVertxProvider.java
extensions/http-client-vertx/runtime/src/main/resources/META-INF/quarkus-extension.yaml
extensions/http-client-vertx/runtime/src/main/resources/META-INF/services/com.azure.core.http.vertx.VertxProvider
extensions/storage-blob/deployment/src/test/java/io/quarkiverse/azureservices/storage/blob/deployment/StorageBlobDevModeTest.java
extensions/storage-blob/deployment/src/test/java/io/quarkiverse/azureservices/storage/blob/deployment/StorageBlobTest.java
extensions/storage-blob/runtime/src/main/java/io/quarkiverse/azureservices/storage/blob/runtime/StorageBlobServiceClientProducer.java
integration-tests/src/main/java/io/quarkiverse/azureservices/storage/blob/it/StorageBlobResource.java

The code that the Camel team contributed, still had the `camel` package name. This gets rid of them

Removes all Camel package name

---

extensions/app-configuration/deployment/src/main/java/io/quarkiverse/azure/app/configuration/deployment/AzureAppConfigurationProcessor.java
extensions/app-configuration/deployment/src/test/java/io/quarkiverse/azure/app/configuration/deployment/AzureAppConfigurationResource.java
extensions/app-configuration/deployment/src/test/java/io/quarkiverse/azure/app/configuration/deployment/AzureAppConfigurationTest.java
extensions/app-configuration/runtime/src/main/java/io/quarkiverse/azure/app/configuration/AzureAppConfigurationConfigSourceFactory.java
integration-tests/app-configuration/pom.xml
integration-tests/app-configuration/src/main/java/io/quarkiverse/azure/app/configuration/it/ConfigResource.java
integration-tests/app-configuration/src/main/resources/application.properties
integration-tests/app-configuration/src/test/java/io/quarkiverse/azure/app/configuration/it/AzureAppConfigurationResource.java
integration-tests/app-configuration/src/test/java/io/quarkiverse/azure/app/configuration/it/AzureAppConfigurationTest.java

Could you please review @radcortez ?
I still wonder why the test application outputs these warnings?
```
[INFO] 2022-12-06 22:56:05,053 WARN  [io.qua.config] (main) Unrecognized configuration key "quarkus.azure.app.configuration.secret" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
[INFO] 2022-12-06 22:56:05,055 WARN  [io.qua.config] (main) Unrecognized configuration key "quarkus.azure.app.configuration.id" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
[INFO] 2022-12-06 22:56:05,056 WARN  [io.qua.config] (main) Unrecognized configuration key "quarkus.azure.app.configuration.endpoint" was provided; it will be ignored; …
```

Simplify app-configuration tests

---

bom/pom.xml
pom.xml

https://github.com/quarkiverse/quarkus-azure-services/pull/53 hit my eyes due to upgrading to netty 2.0.55 that is different from what is Quarkus 2.15.3 using (2.0.54). Investigating further has shown that io.netty:netty-tcnative should not be needed at all. So let's remove it.

Remove superfluous io.netty:netty-tcnative BOM entry

---

docs/modules/ROOT/pages/includes/quarkus-azure-storage-blob.adoc
extensions/azure-storage-blob/deployment/src/main/java/io/quarkiverse/azure/storage/blob/deployment/DevServicesStorageBlobProcessor.java
extensions/azure-storage-blob/deployment/src/test/java/io/quarkiverse/azure/storage/blob/deployment/StorageBlobTestResource.java

Bump azurite to `3.23.0` to support Azure Storage API Version `2022-11-02`, see https://github.com/Azure/Azurite.

Bump azurite to 3.23.0

---

bom/pom.xml

Bump `azure-sdk-bom` to `1.2.13`.

Bump azure sdk to 1.2.13

---

extensions/azure-app-configuration/deployment/src/main/java/io/quarkiverse/azure/app/configuration/deployment/AzureAppConfigurationProcessor.java
extensions/azure-storage-blob/deployment/src/main/java/io/quarkiverse/azure/storage/blob/deployment/StorageBlobProcessor.java
internal/core/deployment/src/main/java/io/quarkiverse/azure/core/deployment/AzureCoreSupportProcessor.java

The PR is to fix the warning `ReflectiveClassBuildItem has been deprecated and marked for removal`, by replacing 'new ReflectiveClassBuildItem()' with 'ReflectiveClassBuildItem.builder()'.
The code changes reference the fix of following issues:
* https://github.com/apache/camel-quarkus/issues/4635
* https://github.com/apache/camel-quarkus/issues/4694

Replace 'new ReflectiveClassBuildItem()' with 'ReflectiveClassBuildItem.builder()'

---

.github/build-with-maven-native.sh
.github/workflows/build.yml
.github/workflows/quarkus-snapshot.yaml
integration-tests/README.md
integration-tests/azure-app-configuration/src/test/java/io/quarkiverse/azure/app/configuration/it/AzureAppConfigurationExternalIT.java
integration-tests/azure-app-configuration/src/test/java/io/quarkiverse/azure/app/configuration/it/AzureAppConfigurationIT.java
integration-tests/azure-storage-blob/src/main/java/io/quarkiverse/azure/storage/blob/it/StorageBlobResource.java
integration-tests/azure-storage-blob/src/main/resources/application.properties

The PR is to resolve #37 by setting up the integration tests against the real Azure services,
* if OICD authentication is enabled in `Build` / `Quarkus ecosystem CI` workflow
* Otherwise run integration tests against mocked Azure services (DevServices or mocked http server) 
Here're two successful runs of `Build` workflow in my fork:
* [run integration tests against real Azure services](https://github.com/majguo/quarkus-azure-services/actions/runs/5150977028)
* [run integration tests against mocked Azure services](https://github.com/majguo/quarkus-azure-services/actions/runs/5150281096)
~~I have already configured a federated identity credential on a user-assigned managed identity (see https://aka.ms/config-federated-identity-on-uami). In order to run tests against the real Azure …

Set up integration tests to run against the real Azure services

---

README.md
extensions/azure-app-configuration/runtime/src/main/resources/META-INF/quarkus-extension.yaml
extensions/azure-storage-blob/runtime/src/main/resources/META-INF/quarkus-extension.yaml
internal/core/runtime/src/main/resources/META-INF/quarkus-extension.yaml
internal/http-client-vertx/runtime/src/main/resources/META-INF/quarkus-extension.yaml
internal/jackson-dataformat-xml/runtime/src/main/resources/META-INF/quarkus-extension.yaml

After upgrading to quarkus 3.0, some errors are observed when running dev mode for `integration-tests/azure-app-configuration` and `integration-tests/azure-storage-blob`.
<details>
<summary>Error details:</summary>
```
2023-06-09 16:29:04,545 ERROR [io.qua.dev.dep.DevUIProcessor] (build-8) Failed to process extension descriptor file:///mnt/c/Users/jiangma/Workspace/repos/quarkus-azure-services/internal/jackson-dataformat-xml/runtime/target/classes/META-INF/quarkus-extension.yaml: java.lang.RuntimeException: Failed to locate 'artifact' or 'group-id' and 'artifact-id' among metadata keys [name, description, metadata]
at io.quarkus.devui.deployment.DevUIProcessor.getExtensionNamespace(DevUIProcessor.java:709)
at io.quarkus.devui.deployment.DevUIProcessor.lambda$getAllExtensions$1(DevUIProcess …
```

Fix malformed metadata in extensions

---

docs/modules/ROOT/pages/quarkus-azure-app-configuration.adoc
docs/modules/ROOT/pages/quarkus-azure-storage-blob.adoc

Asciidoc interprets strings like ${project-version} as attributes and then issues a WARN during the build that it will skip reference to a missing attribute. This PR removes [subs attribute](https://docs.asciidoctor.org/asciidoc/latest/subs/apply-subs-to-blocks/#the-subs-attribute) from code blocks so that Asciidoctor won't perform substitutions inside them.
Proof of all warnings gone:
Proof of warnings before this PR:

Fix all asciidoc warnings

---

bom/pom.xml
docs/pom.xml
extensions/azure-storage-blob/deployment/pom.xml
extensions/azure-storage-blob/runtime/pom.xml
internal/http-client-vertx/deployment/pom.xml
internal/http-client-vertx/deployment/src/main/java/io/quarkiverse/azure/core/http/vertx/deployment/AzureCoreHttpClientVertxProcessor.java
internal/http-client-vertx/pom.xml
internal/http-client-vertx/runtime/pom.xml
internal/http-client-vertx/runtime/src/main/java/io/quarkiverse/azure/core/http/vertx/runtime/QuarkusVertxProvider.java
internal/http-client-vertx/runtime/src/main/resources/META-INF/quarkus-extension.yaml
internal/http-client-vertx/runtime/src/main/resources/META-INF/services/com.azure.core.http.vertx.VertxProvider
internal/pom.xml

After merging #121, I observed a warning message when running the sample app `integration-tests/azure-storage-blob` as a native exectuable:
```
You're already on a Vert.x context, are you sure you want to create a new Vertx instance?
```
After looking around, the warning message is most probably due to calling `Vertx.vertx()` in `com.azure:azure-core-http-vertx`. More details pls see https://github.com/vert-x3/vertx-web/issues/1117.
So the PR is to revert #121 to get rid of the warning message, which is verified locally.

Revert PR 121

---

docs/modules/ROOT/pages/quarkus-azure-app-configuration.adoc
extensions/azure-app-configuration/runtime/src/main/resources/META-INF/quarkus-extension.yaml
extensions/azure-storage-blob/runtime/src/main/resources/META-INF/quarkus-extension.yaml
integration-tests/azure-app-configuration/README.md
integration-tests/azure-storage-blob/README.md

The major change of the PR is to add readme for two sample apps `integration-tests/azure-app-configuration` and `integration-tests/azure-storage-blob`, which supports running the app in:
* `dev` mode
* JVM mode
* Native executable

Add readme for sample apps

---

README.md
integration-tests/README.md
integration-tests/azure-app-configuration/README.md
integration-tests/azure-app-configuration/pom.xml
integration-tests/azure-storage-blob/README.md
integration-tests/azure-storage-blob/pom.xml
integration-tests/pom.xml
pom.xml

The PR is to enhance readme by:
* add release process
* add more badges
* add instructions on deps installation for integ-tests
* add instructions on deps installation for sample apps
It also includes a commit to exclude module `integration-tests` from release, see [this](https://github.com/quarkiverse/quarkiverse/wiki/Release#release-fails-while-deploying-the-integration-tests) for more information.

Update readme and exclude module `integration-tests` from release

---

internal/core/runtime/pom.xml

- Caused by https://github.com/quarkusio/quarkus/pull/34145

Use `graal-sdk` instead of `svm`

---

bom/pom.xml
docs/pom.xml
extensions/azure-app-configuration/runtime/pom.xml
extensions/azure-storage-blob/deployment/pom.xml
extensions/azure-storage-blob/runtime/pom.xml
extensions/pom.xml
integration-tests/azure-app-configuration/pom.xml
integration-tests/azure-storage-blob/pom.xml
internal/jackson-dataformat-xml/deployment/pom.xml
internal/jackson-dataformat-xml/runtime/pom.xml
internal/pom.xml
pom.xml

The PR is to refactor the dependencies management including:
* moving duplicated `dependencyManagement` section to single source `pom.xml` in root folder.
* moving some `properties` from `pom.xml` to `bom/pom.xml` where they're actually used.
* adding missed groupId for some `maven-compiler-plugin`.

Refactor deps mgt

---

README.md
bom/pom.xml
extensions/azure-app-configuration/runtime/pom.xml
extensions/azure-app-configuration/runtime/src/main/java/io/quarkiverse/azure/app/configuration/AzureAppConfigurationConfigSourceFactory.java
extensions/azure-app-configuration/runtime/src/main/resources/META-INF/quarkus-extension.yaml
extensions/azure-storage-blob/runtime/pom.xml
extensions/azure-storage-blob/runtime/src/main/java/io/quarkiverse/azure/storage/blob/runtime/StorageBlobServiceClientProducer.java
extensions/azure-storage-blob/runtime/src/main/resources/META-INF/quarkus-extension.yaml
internal/core/pom.xml
internal/core/runtime/src/main/resources/META-INF/quarkus-extension.yaml
internal/core/util/pom.xml
internal/core/util/src/main/java/io/quarkiverse/azure/core/util/AzureQuarkusIdentifier.java
internal/http-client-vertx/runtime/src/main/resources/META-INF/quarkus-extension.yaml
internal/jackson-dataformat-xml/runtime/src/main/resources/META-INF/quarkus-extension.yaml

The major change of the PR is to set `applicationId` in `ClientOptions` in order to identify the client of relative Azure services is created from Quarkus extension. The PR also updates Quarkiverse documentation site with the new lived `docs.quarkiverse.io`.

Set applicationId in ClientOptions

---

docs/modules/ROOT/pages/quarkus-azure-storage-blob.adoc

Small addition to the documentation about using azure blob store in reactive code, which essentially does not work and cause a fatal hang of the application.
Quarkus issue reported https://github.com/quarkusio/quarkus/issues/37299 which led to this small though useful (in my opinion) documentation update.
I believe a real solution to it would be to allow this extension to produce async client as well, which should play much better with reactive code in quarkus.

added small section about using azure blob store in reactive code

---

integration-tests/azure-app-configuration/src/test/java/io/quarkiverse/azure/app/configuration/it/AzureAppConfigurationWithLabelsIT.java

This PR is a follow-up for #158 to add an integration test running without Azure service for app config with labels.

Add AzureAppConfigurationWithLabelsIT

---

.github/build-with-maven-native.sh
.github/delete-azure-resources.sh
.github/workflows/build.yml
.github/workflows/quarkus-snapshot.yaml

Sometimes app config store is not available when trying to add kv pairs. The PR is to fix the issue by retrieving the connection string with retry-logic. It also makes sure the Azure resources are deleted no matter the job failed or not.

Fix build error

---

.github/project.yml
.github/workflows/build.yml
.github/workflows/release.yml
docs/modules/ROOT/pages/includes/attributes.adoc

Fix the release pipeline failure [Release 1.0.3](https://github.com/quarkiverse/quarkus-azure-services/actions/runs/8891160899).
FYI @galiacheng @edburns

Rollback to 1.0.2 and skip tests depending on azure services in release process

---

.github/project.yml
.github/workflows/build.yml
.github/workflows/release.yml
docs/modules/ROOT/pages/includes/attributes.adoc
integration-tests/azure-keyvault/README.md
integration-tests/azure-keyvault/pom.xml
integration-tests/azure-keyvault/src/test/java/io/quarkiverse/azure/keyvault/secret/it/KeyVaultSecretResourceIT.java
integration-tests/azure-keyvault/src/test/java/io/quarkiverse/azure/keyvault/secret/it/KeyVaultSecretResourceTest.java

We have to disable key-vault tests by default to fix the failure of pipeline [Quarkus ecosystem CI](https://github.com/quarkiverse/quarkus-azure-services/actions/runs/8905600120) and [Quarkiverse Release](https://github.com/quarkiverse/quarkus-azure-services/actions/runs/8905652736), in which there is no real Azure services available.
For pipeline of Build, key-vault tests are enabled with `-Dazure.test=true`.
Cc @galiacheng

Fix build failure

---

.github/build-with-maven-native.sh

The PR is to fix recent pipeline failure by explicitly specifying `--enable-rbac-authorization false` when createing key valut.

Fix recent pipeline failure

---

.github/create-azure-resources.sh
.github/run-integration-test.sh
.github/workflows/build.yml
docs/modules/ROOT/nav.adoc
docs/modules/ROOT/pages/includes/quarkus-azure-eventhubs.adoc
docs/modules/ROOT/pages/includes/quarkus-azure-eventhubs_quarkus.azure.adoc
docs/modules/ROOT/pages/index.adoc
docs/pom.xml
extensions/azure-eventhubs/deployment/pom.xml
extensions/azure-eventhubs/runtime/src/main/java/io/quarkiverse/azure/eventhubs/runtime/EventhubsClientProducer.java
extensions/azure-eventhubs/runtime/src/main/java/io/quarkiverse/azure/eventhubs/runtime/EventhubsConfig.java
integration-tests/README.md
integration-tests/azure-cosmos/README.md
integration-tests/azure-cosmos/src/main/java/io/quarkiverse/azure/cosmos/it/CosmosAsyncResource.java
integration-tests/azure-cosmos/src/test/java/io/quarkiverse/azure/cosmos/it/CosmosAsyncResourceTest.java
integration-tests/azure-cosmos/src/test/java/io/quarkiverse/azure/cosmos/it/CosmosResourceTest.java
integration-tests/azure-eventhubs/README.md
integration-tests/azure-services-disabled/pom.xml
integration-tests/azure-services-disabled/src/main/java/io/quarkiverse/azure/services/disabled/it/EventHubsDisabledResource.java
integration-tests/azure-services-disabled/src/main/resources/application.properties
integration-tests/azure-services-disabled/src/test/java/io/quarkiverse/azure/services/disabled/it/EventHubsDisabledIT.java
integration-tests/azure-services-disabled/src/test/java/io/quarkiverse/azure/services/disabled/it/EventHubsDisabledTest.java
internal/core/util/src/main/java/io/quarkiverse/azure/core/util/AzureQuarkusIdentifier.java

This pull request includes several updates to the Azure integration scripts, documentation, and configurations. The changes primarily focus on improving the integration tests and updating the documentation to reflect the new configurations for Azure Event Hubs.
* Added `-e` to the `set -Euo pipefail` command in `.github/create-azure-resources.sh` and `.github/run-integration-test.sh` to ensure that the shell script exits on any error. [[1]](diffhunk://#diff-0eacc12d5952c41f9c04f0b964de590d1bc0370f2fc1cb34692288587a5eeec9L2-R2) [[2]](diffhunk://#diff-8c48f063e81b678b3cfc7bcc9db009ab6b7d49f189c756e0afe06c8d62e93c03L2-R2)
* Removed the `-B` flag from `mvn` commands to avoid batch mode in `.github/run-integration-test.sh`. [[1]](diffhunk://#diff-8c48f063e81b678b3cfc7bcc9db009ab6b7d49f189c756e0 …

Prepare for the next release

---

common/core/deployment/src/main/java/io/quarkiverse/azure/core/deployment/AzureCoreSupportProcessor.java

The PR is to resolve issue observed when deploy sample integration-tests/azure-storage-blob to aca: 
```
2025-01-20 02:59:49,676 WARN  [com.mic.aad.msa.ManagedIdentityApplication] (Thread-13) [Correlation ID: 911b4f37-8c1c-45a2-8643-5b4560b4ef64] Execution of class com.microsoft.aad.msal4j.AcquireTokenByManagedIdentitySupplier failed: [Managed Identity] Unexpected exception occurred when parsing the response, HttpStatusCode: 200, Error message: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `com.microsoft.aad.msal4j.ManagedIdentityResponse`: cannot deserialize from Object value (no delegate- or property-based Creator): this appears to be a native image, in which case you may need to configure reflection for the class that is to be deserialized …
```

Add reflective class `com.microsoft.aad.msal4j.ManagedIdentityResponse`

---

integration-tests/azure-app-configuration/README.md
integration-tests/azure-cosmos/README.md
integration-tests/azure-eventhubs/README.md
integration-tests/azure-keyvault/README.md
integration-tests/azure-keyvault/src/main/java/io/quarkiverse/azure/keyvault/secret/it/KeyVaultSecretResource.java
integration-tests/azure-keyvault/src/test/java/io/quarkiverse/azure/keyvault/secret/it/KeyVaultSecretResourceTest.java
integration-tests/azure-services-together/README.md
integration-tests/azure-services-together/pom.xml
integration-tests/azure-services-together/src/main/java/io/quarkiverse/azure/services/together/it/KeyVaultSecretResource.java
integration-tests/azure-services-together/src/main/resources/application.properties
integration-tests/azure-services-together/src/test/java/io/quarkiverse/azure/services/together/it/KeyVaultSecretResourceIT.java
integration-tests/azure-services-together/src/test/java/io/quarkiverse/azure/services/together/it/KeyVaultSecretResourceTest.java
integration-tests/azure-storage-blob/README.md

Inspired by #335, this pull request includes multiple changes to various integration test modules and documentation, primarily focusing on adding new test cases for Azure Key Vault secrets to test compatibility with open-telemetry extension, improving test commands and fixing typos. Here are the most important changes:
* Introduced integration test classes for Azure Key Vault secret functionality in the `azure-services-together` module (`integration-tests/azure-services-together/src/test/java/io/quarkiverse/azure/services/together/it/KeyVaultSecretResourceIT.java`, `integration-tests/azure-services-together/src/test/java/io/quarkiverse/azure/services/together/it/KeyVaultSecretResourceTest.java`). [[1]](diffhunk://#diff-551efc454abc80ed8d2577530fdd4edb32a1b1fbf59d6b682560485b05362b58R1-R11) …

Add Azure Key Vault tests and test open-telemetry extension compatibility

---

services/azure-storage-blob/deployment/pom.xml
services/azure-storage-blob/deployment/src/main/java/io/quarkiverse/azure/storage/blob/deployment/DevServicesStorageBlobProcessor.java
services/azure-storage-blob/deployment/src/main/java/io/quarkiverse/azure/storage/blob/deployment/StorageBlobBuildTimeConfig.java
services/azure-storage-blob/deployment/src/main/java/io/quarkiverse/azure/storage/blob/deployment/StorageBlobDevServicesConfig.java

Also adjusted things to use the new DevServicesConfig from core.
We plan to retire the legacy config classes at some point in the future so it's better to move everything to the new @ConfigMapping infrastructure.

Switch to @ConfigMapping for Storage Blob build time config

---

common/azure-identity/runtime/pom.xml
common/core/runtime/pom.xml
common/http-client-vertx/runtime/pom.xml
common/jackson-dataformat-xml/runtime/pom.xml
services/azure-app-configuration/runtime/pom.xml
services/azure-storage-blob/runtime/pom.xml

This pull request introduces updates to the Maven `pom.xml` files for multiple modules, primarily to enhance the configuration of the `quarkus-extension-maven-plugin`. The changes include adding a version property for the plugin, configuring its execution during the compile phase, and formatting improvements for deployment configuration.
* Added the `<version>` property for `quarkus-extension-maven-plugin` and configured its execution to run during the `compile` phase in the following modules:
- `common/azure-identity/runtime/pom.xml`
- `common/core/runtime/pom.xml`
- `common/http-client-vertx/runtime/pom.xml`
- `common/jackson-dataformat-xml/runtime/pom.xml`
* Reformatted the `<deployment>` configuration for better readability in the following modules:
- …

Add execution configuration for quarkus-extension-maven-plugin in pom.xml

---

services/azure-servicebus/deployment/pom.xml
services/azure-servicebus/deployment/src/main/java/ServiceBusProcessor.java
services/azure-servicebus/runtime/pom.xml

With this change, the extension provides its first value to users:
In order to work with the Service Bus, only these dependencies are needed in the project:
```xml
<dependency>
<groupId>io.quarkiverse.azureservices</groupId>
<artifactId>quarkus-azure-servicebus</artifactId>
<version>${quarkus-azure-services.version}</version>
</dependency>
```
or, if MSAL is required,
```xml
<dependency>
<groupId>io.quarkiverse.azureservices</groupId>
<artifactId>quarkus-azure-servicebus</artifactId>
<version>${quarkus-azure-services.version}</version>
</dependency>
<dependency>
<groupId>io.quarkiverse.azureservices</groupId>
<artifactId>quarkus-azure-identity</artifactId>
<version>${quarkus-azure-services.version}</version>
</dependency>
```
For the native build, no configuration is needed. See this …

Support native build

---

docs/modules/ROOT/pages/includes/quarkus-azure-servicebus.adoc
docs/modules/ROOT/pages/includes/quarkus-azure-servicebus_quarkus.azure.adoc
services/azure-servicebus/deployment/pom.xml
services/azure-servicebus/deployment/src/main/java/io/quarkiverse/azure/servicebus/deployment/ServiceBusProcessor.java
services/azure-servicebus/deployment/src/test/java/io/quarkiverse/azure/servicebus/deployment/DisabledDeploymentTest.java
services/azure-servicebus/deployment/src/test/java/io/quarkiverse/azure/servicebus/deployment/EnabledDeploymentTest.java
services/azure-servicebus/runtime/src/main/java/io/quarkiverse/azure/servicebus/runtime/ServiceBusBuildTimeConfig.java
services/azure-servicebus/runtime/src/main/java/io/quarkiverse/azure/servicebus/runtime/ServiceBusClientProducer.java
services/azure-servicebus/runtime/src/main/java/io/quarkiverse/azure/servicebus/runtime/ServiceBusConfig.java

Notes for the reviewer:
- I put `quarkus.azure.servicebus.enabled` in a separate build time configuration so that I can selectively include the CDI producer.
This allows the user of the extension to use his own producers while still benefiting from the module's native image compilation support.
- I included the property names in the error messages so that they become more helpful.

The servicebus extension can produce ServiceBusClientBuilder instances

---

services/azure-app-configuration/runtime/src/main/java/io/quarkiverse/azure/app/configuration/AzureAppConfigurationConfig.java
services/azure-app-configuration/runtime/src/main/java/io/quarkiverse/azure/app/configuration/AzureAppConfigurationConfigSourceFactory.java
services/azure-cosmos/runtime/src/main/java/io/quarkiverse/azure/cosmos/runtime/CosmosClientProducer.java
services/azure-eventhubs/runtime/src/main/java/io/quarkiverse/azure/eventhubs/runtime/EventhubsClientProducer.java
services/azure-keyvault/runtime/src/main/java/io/quarkiverse/azure/keyvault/secret/runtime/KeyVaultSecretClientProducer.java
services/azure-keyvault/runtime/src/main/java/io/quarkiverse/azure/keyvault/secret/runtime/config/KeyVaultSecretConfigUtil.java
services/azure-storage-blob/runtime/src/main/java/io/quarkiverse/azure/storage/blob/runtime/StorageBlobServiceClientProducer.java

#391 introduced property names in the config error messages. This PR adjusts the remaining error messages to be consistent.

Consistency: Include property names in configuration error messagesError messages

---

integration-tests/azure-eventhubs/src/main/java/io/quarkiverse/azure/eventhubs/it/EventhubsAsyncResource.java
integration-tests/azure-eventhubs/src/test/java/io/quarkiverse/azure/eventhubs/it/EventHubsAsyncResourceIT.java
services/azure-cosmos/deployment/src/main/java/io/quarkiverse/azure/cosmos/deployment/CosmosProcessor.java
services/azure-eventhubs/deployment/src/main/java/io/quarkiverse/azure/eventhubs/deployment/EventhubsProcessor.java
services/azure-eventhubs/runtime/pom.xml

This pull request includes updates to the Azure Event Hubs and Cosmos integrations, focusing on test adjustments, dependency cleanup, and runtime configuration improvements. The most significant changes involve modifying test logic for event handling, removing unused dependencies, and adding reflective class support for Cosmos.
* Updated the `sendEvents` method in `EventhubsAsyncResource` to include a new event (`Foobar-Asyn-0`) in the test data.
* Adjusted the `receiveEvents` method in `EventhubsAsyncResource` to account for sequence number modulo logic to handle accumulated events across test runs.
* Fixed a typo in the test class inheritance by changing `EventHubsAsyncResourceIT` to extend `EventHubsAsyncResourceTest` instead of `EventHubsResourceTest`.
* Removed the …

Cleanup and fix AssertionError for Azure Event Hubs integration tests

---

docs/modules/ROOT/pages/includes/quarkus-azure-servicebus.adoc
docs/modules/ROOT/pages/includes/quarkus-azure-servicebus_quarkus.azure.adoc
docs/modules/ROOT/pages/quarkus-azure-servicebus.adoc
integration-tests/azure-servicebus/src/main/resources/application.properties
services/azure-servicebus/deployment/pom.xml
services/azure-servicebus/deployment/src/main/java/io/quarkiverse/azure/servicebus/deployment/ServiceBusBuildTimeConfig.java
services/azure-servicebus/deployment/src/main/java/io/quarkiverse/azure/servicebus/deployment/ServiceBusDevServicesConfig.java
services/azure-servicebus/deployment/src/main/java/io/quarkiverse/azure/servicebus/deployment/ServiceBusDevServicesProcessor.java
services/azure-servicebus/deployment/src/main/java/io/quarkiverse/azure/servicebus/deployment/ServiceBusProcessor.java
services/azure-servicebus/deployment/src/test/java/io/quarkiverse/azure/servicebus/deployment/DeploymentWithDevServicesTest.java
services/azure-servicebus/deployment/src/test/java/io/quarkiverse/azure/servicebus/deployment/DeploymentWithDisabledProducersTest.java
services/azure-servicebus/deployment/src/test/java/io/quarkiverse/azure/servicebus/deployment/DeploymentWithEnabledProducersTest.java
services/azure-servicebus/deployment/src/test/java/io/quarkiverse/azure/servicebus/deployment/DeploymentWithSuppressedDevServicesTest.java
services/azure-servicebus/deployment/src/test/resources/minimal-servicebus-config.json
services/azure-servicebus/runtime/src/main/java/io/quarkiverse/azure/servicebus/runtime/ServiceBusClientProducer.java
services/azure-servicebus/runtime/src/main/java/io/quarkiverse/azure/servicebus/runtime/ServiceBusConfig.java

This is intended as the MVP of new Dev Services for the Azure Service Bus extension.
They manage an Azure Service Bus emulator.
Enhancements for the MVP (feel free to edit the lists):
Enhancements for follow-up PRs:
@majguo PTAL

Add Service Bus Dev Services

---

services/azure-servicebus/deployment/src/main/java/io/quarkiverse/azure/servicebus/deployment/ServiceBusProcessor.java
services/azure-servicebus/runtime/src/main/java/io/quarkiverse/azure/servicebus/runtime/ServiceBusClientProducer.java
services/azure-servicebus/runtime/src/main/java/io/quarkiverse/azure/servicebus/runtime/ServiceBusConfigVerifier.java

Configuration problems that are handled in a CDI producer can cause late deployment errors.
This happens if a produced bean is injected in another bean that is lazily instantiated.
In the context of this Quarkus extension, this means that an application with a REST resource using an injected `ServiceBusClientBuilder` and having neither `quarkus.azure.servicebus.connection-string` nor `quarkus.azure.servicebus.namespace` set, will not fail until the first request to an endpoint provided by the resource is made.
This PR changes this behavior so that the application fails immediately at startup.
It does so by adding a bean with a `@Startup` method that validates the configuration.
See README.md in the attached reproducer application. …

Fail early if the CDI producer is insufficiently configured.

---

docs/modules/ROOT/pages/includes/quarkus-azure-servicebus.adoc
docs/modules/ROOT/pages/includes/quarkus-azure-servicebus_quarkus.azure.adoc
services/azure-servicebus/deployment/pom.xml
services/azure-servicebus/deployment/src/main/java/io/quarkiverse/azure/servicebus/deployment/ServiceBusDevServicesConfig.java
services/azure-servicebus/deployment/src/main/java/io/quarkiverse/azure/servicebus/deployment/ServiceBusDevServicesDatabaseConfig.java
services/azure-servicebus/deployment/src/main/java/io/quarkiverse/azure/servicebus/deployment/ServiceBusDevServicesEmulatorConfig.java
services/azure-servicebus/deployment/src/main/java/io/quarkiverse/azure/servicebus/deployment/ServiceBusDevServicesProcessor.java

The container images for the Azure Service Bus emulator and the MSSQL Server can now be configured.
The default images use the `latest` image tag instead of a specific version.
This means that users using the default configuration always get the most current version of the emulator. This might break tests if there are incompatible changes in newer emulator versions. Therefore the docs recommend to use specific image versions and include a recommended version.

The images used by the Azure Service Bus Dev Services can be configured.

---

docs/modules/ROOT/pages/quarkus-azure-servicebus.adoc
services/azure-servicebus/deployment/src/main/java/io/quarkiverse/azure/servicebus/deployment/ServiceBusDevServicesProcessor.java

This PR adds documentation for the Azure Service Bus Dev Services: what they actually do, that licenses have to be accepted, how to disable them.
I also changed the link to the EULA for the MSSQL Server in the existing docs. It used to point to the container documentation, where the relevant section could not be targeted by a link. The new URL points to the EULA directly. Sadly, the document is in RTF format, meaning it will not open in the browser but be downloaded. Still not perfect, but I think it's better.

Documentation for the Azure Service Bus Dev Services

---

services/azure-servicebus/deployment/src/main/java/io/quarkiverse/azure/servicebus/deployment/ServiceBusDevServicesProcessor.java

Due to missing brackets, the message would be "Using" instead of "Using a shared network" when a shared network was used.

Fix log message

---

.github/project.yml
README.md
docs/modules/ROOT/pages/includes/attributes.adoc
integration-tests/azure-app-configuration/README.md
integration-tests/azure-cosmos/README.md
integration-tests/azure-eventhubs/README.md
integration-tests/azure-keyvault/README.md
integration-tests/azure-servicebus/README.md
integration-tests/azure-services-together/README.md
integration-tests/azure-storage-blob/README.md

This pull request updates the project version from 1.1.9 to 1.2.0 across the documentation and configuration files, ensuring consistency and reflecting the new release. It also updates compatibility information and usage instructions to reference the new version.
Version updates and documentation:
* Project version is updated to 1.2.0 in the main configuration file `.github/project.yml` and in the documentation attributes (`:project-version:`) to reflect the new release. [[1]](diffhunk://#diff-735957720c86e5ec3ee129d26dde30a1fd6b7e485100843ef9b576269eb065e9L2-R2) [[2]](diffhunk://#diff-6a9cf7ce7ec74bc87cf4d9b920b636a61915b0ad2683689d9ee8280a1debbf37L1-R1)
* All integration test `README.md` files are updated to use version 1.2.0 in their example `pom.xml` snippets and instructions, …

Release 1.2.0
